export const USERNAME_INPUT = 'USERNAME_INPUT';
export const PASSWORD_INPUT = 'PASSWORD_INPUT';
export const LOGIN_BUTTON = 'LOGIN_BUTTON';
export const REGISTER_BUTTON = 'REGISTER_BUTTON';

export const USERNAME_DISPLAY = 'USERNAME_DISPLAY';
